[toolchain]
anchor_version = "0.31.1"

[features]
seeds = false
skip-lint = false

[workspace]
members = ["shopsage-payment", "shopsage-expert", "shopsage-session"]

[programs.localnet]
shopsage-payment = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
shopsage-expert = "H9yJ6t8VN7jRmE3sKuPnXbfWVv5qgZt8VnKmHx2FdvGE"
shopsage-session = "J8bL4qVx2cRtGnMfHs3XzNvK4wYt7PzHdC9qFrE6aWuG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
