//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "shopper_profiles")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub id: Uuid,
  pub user_id: Uuid,
  pub categories: Json,
  #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
  pub price_range_min: Decimal,
  #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
  pub price_range_max: Decimal,
  pub preferred_experts: Json,
  pub saved_experts: Json,
  pub interests: Json,
  pub total_sessions: i32,
  #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
  pub total_spent: Decimal,
  #[sea_orm(column_type = "Decimal(Some((3, 2)))")]
  pub average_rating: Decimal,
  pub created_at: DateTimeWithTimeZone,
  pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(
    belongs_to = "super::users::Entity",
    from = "Column::UserId",
    to = "super::users::Column::Id",
    on_update = "NoAction",
    on_delete = "Cascade"
  )]
  Users,
}

impl Related<super::users::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Users.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
